package com.wordwaverise.wordwaveriseapp.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "flashcards")
data class FlashcardEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val serverId: Int? = null,  // ID on the backend for syncing reviews
    val word: String,
    val definition: String,
    val example: String? = null,
    val translation: String? = null,
    val phonetic: String? = null,
    val partOfSpeech: String? = null,

    /**
     * The folder, as the *server* numbers folders — the same id `CategoryEntity.serverId`
     * carries. Local category rows are keyed by an autogenerated `id` that means nothing to the
     * API, so storing that one here would filter correctly on this device and nowhere else.
     */
    val serverCategoryId: Int? = null,

    /** Hand-edited: the dictionary refresh must leave this card's wording alone. */
    val customized: Boolean = false,

    /** Which sense of the article this card is about, when the user pinned one. */
    val senseId: String? = null,

    // Spaced repetition fields (local)
    val repetitionLevel: Int = 0,
    val lastReviewed: Long? = null,
    val nextReviewDate: Long = System.currentTimeMillis(),
    val correctCount: Int = 0,
    val incorrectCount: Int = 0,

    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)
